repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: check-file-length
        name: Check file length (max 500 lines)
        entry: python scripts/check_file_length.py
        language: system
        files: \.py$
        exclude: ^tests/
        pass_filenames: true
      - id: check-no-emojis
        name: Check no emojis in files
        entry: python scripts/check_no_emojis.py
        language: system
        pass_filenames: true